### ISSUE TITLE
error for future reference

### ISSUE THREAD

**Issue by Bluethefurry** [IllusiveTea/sentryio-fivem#2]
Error running system event handling function for resource SentryIO-FiveM: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: sentry.lua:15: bad argument #1 to 'date' (invalid conversion specifier '%TZ')

**Comment by vecchiotom** [comment]
owo

**Comment by Bluethefurry** [comment]
fixed in https://github.com/IllusiveTea/sentryio-fivem/commit/3f9f8225e12a54d4fbabfb00a1df03d6344d9906
